List<String> product = [
  'Mi Electric Scooter 3',
  'Mi Electric Scooter Pro 2',
  'Mi Electric Scooter 1S',
  'Mi Electric Scooter Essential',
  'Mi Smart Electric Toothbrush T500',
  'Mi Casual Daypack',
  'Mi Mouse Portable',
  'Mi Smart Band 5 Strap (3-Pack)',
  'Mi Type-C Braided Cable',
  'Mi Selfie Stick Tripod',
  'Amazfit Pace',
  'Mi In-Ear Headphones Basic',
  'Amazfit T-Rex',
  'Mi Smart Band 3/4 Strap',
  'Mi Smart Band 6 Strap (3-Pack)',
  'Mi Smart Band 4 Strap',
  'Mi Vacuum Cleaner G10/G9 HEPA Filter Kit',
  'Mi City Backpack',
  'Mi Business Backpack',
  'Mi Watch Strap (3-Pack)',
  'Mi City Sling Bag',
  'Mi Casual Backpack',
  'Mi Urban Backpack',
  'Mi Dual Mode Wireless Mouse Silent Edition',
  'Mi Robot Vacum Mop 2 Pro',
  'Mi Robot Vacum Mop 2',
  'Mi Robot Vacum Mop 2 Lite',
  'Mi Robot Vacum Mop P',
  'Mi Robot Vacum Mop',
  'Mi Handheld Vacuum Cleaner',
  'Mi Vacuum Cleaner G10',
  'Xiaomi Smart Air Purifier 4 Pro',
  'Xiaomi Smart Air Purifier 4',
  'Xiaomi Smart Air Purifier 4 Lite',
  'Mi Air Purifier 3H',
  'Mi Vacuum Cleaner Mini',
  'Mi Vacuum Cleaner Light',
  'Mi Smart Air Fryer 3.5L',
  'Mi True Wireless Earbuds Basic 2',
  'Mi True Wireless Earbuds Basic S',
  'Mi Bluetooth Headset Basic',
  'Mi Bluetooth Headset mini',
  'Mi True Wireless Earphones',
  'Mi True Wireless Earphones Lite',
  'Redmi Buds 3 Pro',
  'Mi True Wireless Earphones 2 Basic',
  'Mi True Wireless Earphones 2S',
  'Mi Home Security Camera 360° 1080P',
  'Mi 360° Home Security Camera 2K',
  'Mi 360° Camera (1080p)',
  'Mi Wireless Outdoor Security Camera 1080p Set',
  'Mi Wireless Outdoor Security Camera 1080p',
  'Mi Wireless Charging Pad',
  'Mi 20W Wireless Car Charger',
  'Mi Power Bank 3 Pro 20000mAh',
  'Mi Car Charger Pro',
  'Mi Smart Band 4 Charging Cable',
  'Mi 2-in-1 USB Cable 30cm',
  'Mi 37W Dual-Port Car Charger',
  'Mi Wireless Power Bank Essential 10000mAh',
  'Mi 20W Wireless Charging Stand',
  'Mi 2-in-1 USB Cable 100cm',
  'Mi 18W Fast Charge Power Bank 3 10000mAh',
  'Redmi 18W Fast Charge Power Bank 20000mAh',
  'Redmi Power Bank 10000mAh',
  'Mi Electric Toothbrush Head (3-pack, regular)',
  'Mi Electric Toothbrush Head (Gum Care)',
  'Mi Smart Scale 2',
  'Mi Body Composition Scale 2',
  'Mi Bedside Lamp 2',
  'Mi LED Desk Lamp 1S',
  'Mi Smart LED Smart Bulb Essential (White and Color)',
  'Mi Smart LED Bulb  (White and Color)',
  'Mi Motion-Activated Night Light 2',
  'Mi Window and Door Sensor',
  'Mi Temperature and Humidity Sensor',
  'Mi Wireless Switch',
  'Mi Temperature and Humidity Monitor',
  'Mi Smart Sensor Set',
  'Mi Temperature and Humidity Monitor 2',
  'Mi Motion Sensor',
  'Mi Box S',
  'Mi TV Stick',
  'Mi Smart Compact Projector',
  'Amazfit Bip S',
  'Amazfit Verge',
  'Amazfit GTR 42mm',
  'Amazfit GTR 47mm',
  'Mi Watch',
  'Mi Watch Lite',
  'Mi Smart Band 5',
  'Mi Smart Band 6',
  'Redmi Watch 2 Lite',
  'Mi 50W Power Bank 20000mAh',
  'Mi Electric Shaver S500',
  'Mi 5-Blade Electric Shaver',
  'Mi Cordless Screwdriver',
  'Mi 16-in-1 Ratchet Screwdriver',
  'Mi Portable Bluetooth Speaker（16W）',
  'Xiaomi Watch S1',
  'Xiaomi Watch S1 Active',
  'Redmi Buds 3 Lite',
  'Redmi Buds 3',
  'Xaiomi Buds 3T Pro',
  'Xiaomi Buds 3',
  'Mi Electric Kettle',
  'Mi Smart Standing Fan 1X'
];

List<String> color = [
  'White',
  'Black',
  'Aluminum alloy',
  'Army Green',
  'Beige',
  'Black/Orange/Blue',
  'Black/Orange/Teal',
  'Blue',
  'Blue/Yellow/Mint Green',
  'Brilliant Blue',
  'Camo, Khaki',
  'Carbon Black',
  'Cherry Blossom Pink',
  'Coral Red',
  'Dark Grey',
  'Glacier Gray',
  'Gold',
  'Graphite Black',
  'Grey',
  'Ivory',
  'Ivory/Olive/Yellow',
  'Light Grey',
  'Moon White',
  'Moonlight White',
  'Navy Blue',
  'Ocean Blue',
  'Olive',
  'Olive/Yellow/Orange',
  'Orange',
  'Pink',
  'Red',
  'Rock Black',
  'Silver',
  'Space Black',
  'Stainless steel',
  'Starry Black',
  'Titanium'
];
